# Converting Geonames TSV to GeoPackage

In [5]:
import os
import pandas as pd
import geopandas as gpd

In [6]:
filename = 'data/cities500.txt'

In [7]:
column_names = [
    'geonameid', 'name', 'asciiname', 'alternatenames', 
    'latitude', 'longitude', 'feature class', 'feature code',
    'country code', 'cc2', 'admin1 code', 'admin2 code',
    'admin3 code', 'admin4 code', 'population', 'elevation',
    'dem', 'timezone', 'modification date'
]

df = pd.read_csv(filename, sep='\t', names=column_names)
df

/Users/ujaval/opt/anaconda3/envs/python_foundation/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (13) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,geonameid,name,asciiname,alternatenames,latitude,longitude,feature class,feature code,country code,cc2,admin1 code,admin2 code,admin3 code,admin4 code,population,elevation,dem,timezone,modification date
0,3038999,Soldeu,Soldeu,NaN,42.57688,1.66769,P,PPL,AD,NaN,02,NaN,NaN,NaN,602,NaN,1832,Europe/Andorra,2017-11-06
1,3039154,El Tarter,El Tarter,"Ehl Tarter,Эл Тартер",42.57952,1.65362,P,PPL,AD,NaN,02,NaN,NaN,NaN,1052,NaN,1721,Europe/Andorra,2012-11-03
2,3039163,Sant Julià de Lòria,Sant Julia de Loria,"San Julia,San Julià,Sant Julia de Loria,Sant J...",42.46372,1.49129,P,PPLA,AD,NaN,06,NaN,NaN,NaN,8022,NaN,921,Europe/Andorra,2013-11-23
3,3039604,Pas de la Casa,Pas de la Casa,"Pas de la Kasa,Пас де ла Каса",42.54277,1.73361,P,PPL,AD,NaN,03,NaN,NaN,NaN,2363,2050.0,2106,Europe/Andorra,2008-06-09
4,3039678,Ordino,Ordino,"Ordino,ao er di nuo,orudino jiao qu,Ордино,オルデ...",42.55623,1.53319,P,PPLA,AD,NaN,05,NaN,NaN,NaN,3066,NaN,1296,Europe/Andorra,2018-10-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196476,895269,Beitbridge,Beitbridge,"Bajtbridz,Bajtbridzh,Beitbridge,Beitbridzas,Be...",-22.21667,30.00000,P,PPL,ZW,NaN,07,NaN,NaN,NaN,26459,NaN,461,Africa/Harare,2013-03-12
196477,895308,Beatrice,Beatrice,Beatrice,-18.25283,30.84730,P,PPL,ZW,NaN,04,NaN,NaN,NaN,1647,NaN,1307,Africa/Harare,2018-05-09
196478,895417,Banket,Banket,"Banket,Banket Junction",-17.38333,30.40000,P,PPL,ZW,NaN,05,NaN,NaN,NaN,9641,NaN,1277,Africa/Harare,2013-03-12
196479,1085510,Epworth,Epworth,Epworth,-17.89000,31.14750,P,PPLX,ZW,NaN,10,NaN,NaN,NaN,123250,NaN,1508,Africa/Harare,2012-01-19
196480,1106542,Chitungwiza,Chitungwiza,"Chitungviza,Chitungwiza,Chytungviza,Citungviza...",-18.01274,31.07555,P,PPL,ZW,NaN,10,NaN,NaN,NaN,340360,NaN,1435,Africa/Harare,2019-09-05

In [8]:
geometry = gpd.points_from_xy(df.longitude, df.latitude)
gdf = gpd.GeoDataFrame(df, crs='EPSG:4326', geometry=geometry)
print(gdf.info())

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 196481 entries, 0 to 196480
Data columns (total 20 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   geonameid          196481 non-null  int64
 1   name               196481 non-null  object
 2   asciiname          196464 non-null  object
 3   alternatenames     161429 non-null  object
 4   latitude           196481 non-null  float64
 5   longitude          196481 non-null  float64
 6   feature class      196481 non-null  object
 7   feature code       196480 non-null  object
 8   country code       196436 non-null  object
 9   cc2                6379 non-null    object
 10  admin1 code        196446 non-null  object
 11  admin2 code        149897 non-null  object
 12  admin3 code        88595 non-null   object
 13  admin4 code        32443 non-null   object
 14  population         196481 non-null  int64
 15  elevation          33340 non-null   float64
 16  dem                196481 non-null  int64
 17  timezone           196481 non-null  object
 18  modification date  196481 non-null  object
 19  geometry           196481 non-null  geometry
dtypes: float64(3), geometry(1), int64(3), object(13)
memory usage: 30.0+ MB
None

In [11]:
output_dir = 'output'
output_filename = 'us_cities.gpkg'
output_path = os.path.join(output_dir, output_filename)

filtered = gdf[gdf['country code'] == 'US']
filtered.to_file(driver='GPKG', filename=output_path, encoding='utf-8')
print('Successfully written output file at {}'.format(output_path))

Successfully written output file at output/us_cities.gpkg

----